/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 .\bow_and_arrow.glb --transform --types
Author: Manojkumar (https://sketchfab.com/manojmano344)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/bow-and-arrow-88c886f000004ed894bae54000205b33
Title: Bow And Arrow
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    string1_string2_0: THREE.Mesh;
    limb_lambert1_0: THREE.Mesh;
    grip_grip1_0: THREE.Mesh;
    shaft_shaft1_0: THREE.Mesh;
    Arrow_point_arrow_point_0: THREE.Mesh;
    rope_grip2_0: THREE.Mesh;
    fletching_fletching1_0: THREE.Mesh;
  };
  materials: {
    string2: THREE.MeshStandardMaterial;
    lambert1: THREE.MeshStandardMaterial;
    grip1: THREE.MeshStandardMaterial;
    shaft1: THREE.MeshStandardMaterial;
    arrow_point: THREE.MeshStandardMaterial;
    fletching1: THREE.MeshStandardMaterial;
  };
};

export default function Bow(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    'bow_and_arrow-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.25}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.string1_string2_0.geometry}
            material={materials.string2}
          />
          <mesh
            geometry={nodes.limb_lambert1_0.geometry}
            material={materials.lambert1}
            position={[0, -0.49, 0]}
          />
          <mesh
            geometry={nodes.grip_grip1_0.geometry}
            material={materials.grip1}
          />
          <mesh
            geometry={nodes.shaft_shaft1_0.geometry}
            material={materials.shaft1}
          />
          <mesh
            geometry={nodes.Arrow_point_arrow_point_0.geometry}
            material={materials.arrow_point}
          />
          <mesh
            geometry={nodes.rope_grip2_0.geometry}
            material={materials.grip1}
          />
          <mesh
            geometry={nodes.fletching_fletching1_0.geometry}
            material={materials.fletching1}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('bow_and_arrow-transformed.glb');
