/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./fireplace.glb --transform --types
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Model_material1_0_1: THREE.Mesh;
    Model_material1_0_2: THREE.Mesh;
    Model_material1_0_3: THREE.Mesh;
  };
  materials: {
    material1: THREE.MeshBasicMaterial;
    material0: THREE.MeshBasicMaterial;
    material2: THREE.MeshBasicMaterial;
  };
};

export default function Fireplace(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    'fireplace-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[2.47, 0.1, -0.1]} scale={0.14}>
        <group rotation={[Math.PI, 0, 0]}>
          <mesh
            geometry={nodes.Model_material1_0_1.geometry}
            material={materials.material1}
          />
          <mesh
            geometry={nodes.Model_material1_0_2.geometry}
            material={materials.material0}
          />
          <mesh
            geometry={nodes.Model_material1_0_3.geometry}
            material={materials.material2}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('fireplace-transformed.glb');
