/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ..\..\public\sword.gltf --transform --types
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    mesh: THREE.Mesh;
    mesh_1: THREE.Mesh;
  };
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('sword-transformed.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, -0.13, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={11.84}
      >
        <mesh
          geometry={nodes.mesh.geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes.mesh_1.geometry}
          material={materials['Material.002']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('sword-transformed.glb');
