/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./terrain.gltf --transform --types
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Landscape: THREE.Mesh;
  };
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial;
  };
};

export default function Terrain(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('terrain-transformed.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Landscape.geometry}
        material={materials['Material.001']}
      />
    </group>
  );
}

useGLTF.preload('terrain-transformed.glb');
